/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarksburgdbms.actionforms.edit;
import clarksburgdbms.Main;
import clarksburgdbms.choiceforms.Edit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EditStaff extends javax.swing.JFrame {

    Connection connection;
    /**
     * Creates new form AddStaff
     */
    public EditStaff() {
        initComponents();
        
        String url = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/cpetza1db";
        String username = "cpetza1";
        String password = "COSC*l1j11";
        
        try {
            connection = DriverManager.getConnection(url, username, password); 
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ssnField = new javax.swing.JTextField();
        fnameField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        mnameField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        titleField = new javax.swing.JTextField();
        codeField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        addButton2 = new javax.swing.JButton();
        addButton3 = new javax.swing.JButton();
        addButton4 = new javax.swing.JButton();
        addButton5 = new javax.swing.JButton();
        addButton7 = new javax.swing.JButton();
        addButton8 = new javax.swing.JButton();
        addButton9 = new javax.swing.JButton();
        addButton10 = new javax.swing.JButton();
        addButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        ViewStaffButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setText("Edit Staff");

        jLabel1.setText("SSN:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Middle Name:");

        jLabel6.setText("Salary:");

        jLabel7.setText("Address:");

        jLabel8.setText("Job Title:");

        jLabel9.setText("Job Code:");

        jLabel10.setText("DOB:");

        jLabel11.setText("Job Type:");

        addButton.setText("Edit All");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAllButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        addButton2.setText("Edit");
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFirstNameButtonActionPerformed(evt);
            }
        });

        addButton3.setText("Edit");
        addButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLastNameButtonActionPerformed(evt);
            }
        });

        addButton4.setText("Edit");
        addButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMiddleNameButtonActionPerformed(evt);
            }
        });

        addButton5.setText("Edit");
        addButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSalaryButtonActionPerformed(evt);
            }
        });

        addButton7.setText("Edit");
        addButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAddressButtonActionPerformed(evt);
            }
        });

        addButton8.setText("Edit");
        addButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJobTitleButtonActionPerformed(evt);
            }
        });

        addButton9.setText("Edit");
        addButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJobCodeButtonActionPerformed(evt);
            }
        });

        addButton10.setText("Edit");
        addButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDOBButtonActionPerformed(evt);
            }
        });

        addButton11.setText("Edit");
        addButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJobTypeButtonActionPerformed(evt);
            }
        });

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SSN", "First", "Middle", "Last", "Salary", "Address", "Job Title", "Job Code", "DOB", "Job Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(staffTable);

        ViewStaffButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewStaffButton.setText("View Staff");
        ViewStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStaffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ssnField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(12, 12, 12)
                                        .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(12, 12, 12)
                                        .addComponent(mnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(12, 12, 12)
                                        .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(19, 19, 19)
                                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(addButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(17, 17, 17)
                                                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(addButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(addButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(addButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton)
                        .addGap(217, 217, 217)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(408, 408, 408))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ViewStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeButton)
                            .addComponent(backButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton7)
                    .addComponent(ssnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton2)
                    .addComponent(addButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton3)
                    .addComponent(addButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton4)
                    .addComponent(addButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton5)
                    .addComponent(addButton11))
                .addGap(32, 32, 32)
                .addComponent(addButton)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void editAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAllButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET "
                    + "FNAME='"+fnameField.getText()+"', "
                    + "MNAME='"+mnameField.getText()+"', "
                    + "LNAME='"+lnameField.getText()+"', "
                    + "SALARY='"+salaryField.getText()+"', "
                    + "ADDRESS='"+addressField.getText()+"', "
                    + "JOB_TITLE='"+titleField.getText()+"', "
                    + "JOB_CODE='"+codeField.getText()+"', "
                    + "DOB='"+dobField.getText()+"', "
                    + "JOB_TYPE='"+typeField.getText()+"' "
                    + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
//        fnameField.setText(null);
//        mnameField.setText(null);
//        lnameField.setText(null);
//        salaryField.setText(null);
//        addressField.setText(null);
//        titleField.setText(null);
//        codeField.setText(null);
//        dobField.setText(null);
//        typeField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editAllButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new Edit().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void editFirstNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFirstNameButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET FNAME='"+fnameField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff first name has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        fnameField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editFirstNameButtonActionPerformed

    private void editLastNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLastNameButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET LNAME='"+lnameField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff last name has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        lnameField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editLastNameButtonActionPerformed

    private void editMiddleNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMiddleNameButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET MNAME='"+mnameField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff middle name has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        mnameField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editMiddleNameButtonActionPerformed

    private void editSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSalaryButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET SALARY='"+salaryField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff salary has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        salaryField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editSalaryButtonActionPerformed

    private void editAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddressButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET ADDRESS='"+addressField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff address has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        addressField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editAddressButtonActionPerformed

    private void editJobTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJobTitleButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET JOB_TITLE='"+titleField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff job title has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        titleField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editJobTitleButtonActionPerformed

    private void editJobCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJobCodeButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET JOB_CODE='"+codeField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff job code has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        codeField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editJobCodeButtonActionPerformed

    private void editDOBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDOBButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET DOB='"+dobField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff DOB has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        dobField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editDOBButtonActionPerformed

    private void editJobTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJobTypeButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STAFF "
                + "SET JOB_TYPE='"+typeField.getText()+"' "
                + "WHERE SSN='"+ssnField.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Staff job type has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        typeField.setText(null);
        
        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_editJobTypeButtonActionPerformed

    private void ViewStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStaffButtonActionPerformed
        try {
        String Query = "USE cpetza1db";  // Select the database
            Statement stmt = connection.createStatement();
            stmt.execute(Query);
        String query = "SELECT * FROM STAFF";
            PreparedStatement pstmt = connection.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel)staffTable.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),
               rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), });
            }
        } catch(SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_ViewStaffButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewStaffButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton10;
    private javax.swing.JButton addButton11;
    private javax.swing.JButton addButton2;
    private javax.swing.JButton addButton3;
    private javax.swing.JButton addButton4;
    private javax.swing.JButton addButton5;
    private javax.swing.JButton addButton7;
    private javax.swing.JButton addButton8;
    private javax.swing.JButton addButton9;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField codeField;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField fnameField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField mnameField;
    private javax.swing.JTextField salaryField;
    private javax.swing.JTextField ssnField;
    private javax.swing.JTable staffTable;
    private javax.swing.JTextField titleField;
    private javax.swing.JTextField typeField;
    // End of variables declaration//GEN-END:variables
}
