/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarksburgdbms.actionforms.edit;
import clarksburgdbms.Main;
import clarksburgdbms.choiceforms.Edit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class EditStudent extends javax.swing.JFrame {

    /**
     * Creates new form EditStudent
     */
    public EditStudent() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        AddButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        middleName = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        parentalContact = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        ethnicity = new javax.swing.JTextField();
        commuterType = new javax.swing.JTextField();
        educationPlan = new javax.swing.JTextField();
        emergencyContact = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        medInfo = new javax.swing.JTextField();
        homeRoom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        attendance = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        guardianSSN = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        principalSSN = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        asaSSN = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        attenSecSSN = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddButton1 = new javax.swing.JButton();
        AddButton2 = new javax.swing.JButton();
        AddButton4 = new javax.swing.JButton();
        AddButton5 = new javax.swing.JButton();
        AddButton6 = new javax.swing.JButton();
        AddButton7 = new javax.swing.JButton();
        AddButton8 = new javax.swing.JButton();
        AddButton9 = new javax.swing.JButton();
        AddButton10 = new javax.swing.JButton();
        AddButton11 = new javax.swing.JButton();
        AddButton12 = new javax.swing.JButton();
        AddButton13 = new javax.swing.JButton();
        AddButton14 = new javax.swing.JButton();
        AddButton15 = new javax.swing.JButton();
        AddButton16 = new javax.swing.JButton();
        AddButton17 = new javax.swing.JButton();
        AddButton18 = new javax.swing.JButton();
        AddButton19 = new javax.swing.JButton();
        AddButton20 = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        ViewStaffButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable2 = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        AddButton.setText("Edit");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonFirstNameActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Middle Name");

        jLabel3.setText("Last Name");

        jLabel5.setText("Address");

        jLabel7.setText("Ethnicity");

        jLabel8.setText("Commuter Type");

        jLabel9.setText("Emergency Contact");

        jLabel10.setText("Education Plan");

        jLabel11.setText("Home Room Number");

        jLabel12.setText("Phone Number");

        jLabel13.setText("Medication Information");

        jLabel15.setText("Parental Contact");

        jLabel16.setText("Birthdate(YYYY-MM-DD)");

        jLabel17.setText("ID");

        jLabel18.setText("Attendance");

        jLabel19.setText("Guardian SSN");

        jLabel20.setText("Grade");

        jLabel21.setText("Principal SSN");

        jLabel22.setText("ASA SSN");

        jLabel23.setText("Atten Sec SSN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Edit Student");

        AddButton1.setText("Edit All");
        AddButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonAllActionPerformed(evt);
            }
        });

        AddButton2.setText("Edit");
        AddButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonLastNameActionPerformed(evt);
            }
        });

        AddButton4.setText("Edit");
        AddButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonMiddleNameActionPerformed(evt);
            }
        });

        AddButton5.setText("Edit");
        AddButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonEthnicityActionPerformed(evt);
            }
        });

        AddButton6.setText("Edit");
        AddButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonBIrthdateActionPerformed(evt);
            }
        });

        AddButton7.setText("Edit");
        AddButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonHomeRoomNumberActionPerformed(evt);
            }
        });

        AddButton8.setText("Edit");
        AddButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonAttendanceActionPerformed(evt);
            }
        });

        AddButton9.setText("Edit");
        AddButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonEmergencyContactActionPerformed(evt);
            }
        });

        AddButton10.setText("Edit");
        AddButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonEducationPlanActionPerformed(evt);
            }
        });

        AddButton11.setText("Edit");
        AddButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonPhoneNumberActionPerformed(evt);
            }
        });

        AddButton12.setText("Edit");
        AddButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonParentalContactActionPerformed(evt);
            }
        });

        AddButton13.setText("Edit");
        AddButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonGuardianSSNActionPerformed(evt);
            }
        });

        AddButton14.setText("Edit");
        AddButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonAddressActionPerformed(evt);
            }
        });

        AddButton15.setText("Edit");
        AddButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonCommuterTypeActionPerformed(evt);
            }
        });

        AddButton16.setText("Edit");
        AddButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonGradeActionPerformed(evt);
            }
        });

        AddButton17.setText("Edit");
        AddButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonPrincipalSSNActionPerformed(evt);
            }
        });

        AddButton18.setText("Edit");
        AddButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonASASSNActionPerformed(evt);
            }
        });

        AddButton19.setText("Edit");
        AddButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonAttenSecSSNActionPerformed(evt);
            }
        });

        AddButton20.setText("Edit");
        AddButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonMedicationInformationActionPerformed(evt);
            }
        });

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        ViewStaffButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewStaffButton.setText("View Students");
        ViewStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStaffButtonActionPerformed(evt);
            }
        });

        studentTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "First", "Middle", "Last", "ASA SSN", "Attendance SSN", "Address", "Parent Contact", "DOB", "Ethnicity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable1);

        studentTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Studfent ID", "Commuter Type", "Attendance", "Emergency Contact", "Education Plan", "Homeroom", "Phone", "Medical Info", "Guardian SSN", "Grade Report ID", "Principal SSN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(studentID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(educationPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(parentalContact, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardianSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(commuterType, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(principalSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(homeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(medInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(asaSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(attenSecSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(homeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backButton)
                                .addGap(255, 255, 255)
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(AddButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(ViewStaffButton)
                                .addGap(9, 9, 9))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dob, ethnicity, firstName, homeRoom, lastName, middleName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {address, asaSSN, attenSecSSN, commuterType, educationPlan, emergencyContact, grade, guardianSSN, parentalContact, phoneNumber, principalSSN});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel12, jLabel15, jLabel19, jLabel20, jLabel21, jLabel22, jLabel23, jLabel5, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel11, jLabel16, jLabel17, jLabel18, jLabel2, jLabel3, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeButton)
                            .addComponent(backButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewStaffButton))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(emergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(educationPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(parentalContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(guardianSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton14)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(commuterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AddButton15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(principalSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(asaSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddButton18))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(medInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddButton20))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(attenSecSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddButton19)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {attendance, dob, ethnicity, firstName, homeRoom, lastName, middleName, studentID});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {address, asaSSN, attenSecSSN, commuterType, educationPlan, emergencyContact, grade, guardianSSN, parentalContact, phoneNumber, principalSSN});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel12, jLabel15, jLabel19, jLabel20, jLabel21, jLabel22, jLabel23, jLabel5, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel11, jLabel16, jLabel17, jLabel18, jLabel2, jLabel3, jLabel7});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String url = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/cpetza1db";
    String username = "cpetza1";
    String password = "COSC*l1j11";
    
    private void EditButtonFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonFirstNameActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET FNAME='"+firstName.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student first name has been changed");
        
//        firstName.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonFirstNameActionPerformed

    private void EditButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonAllActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
        + "SET "
            + "FNAME='"+firstName.getText()+"', "
            + "MNAME='"+middleName.getText()+"', "
            + "LNAME='"+lastName.getText()+"', "
            + "STU_ASA_SSN='"+asaSSN.getText()+"', "
            + "STU_ATTEN_SEC_SSN='"+attenSecSSN.getText()+"', "
            + "ADDRESS='"+address.getText()+"', "
            + "DOB='"+dob.getText()+"', "
            + "ETHNICITY='"+ethnicity.getText()+"', "
            + "COMMUTER_TYPE='"+commuterType.getText()+"', "
            + "ATTENDENCE='"+attendance.getText()+"', "
            + "EMERGENCY_CONTECT='"+emergencyContact.getText()+"', "
            + "EDUCATION_PLAN='"+educationPlan.getText()+"', "
            + "HOMEROOM_NO='"+homeRoom.getText()+"', "
            + "PHONE_NO='"+phoneNumber.getText()+"', "
            + "MEDICAL_INFORMATION='"+medInfo.getText()+"', "
            + "PARENTAL_CONTACT='"+parentalContact.getText()+"', "
            + "STU_GUARDIAN_SSN='"+guardianSSN.getText()+"', "
            + "STU_GRADE_ID='"+grade.getText()+"', "
            + "STU_P_SSN='"+principalSSN.getText()+"' "
        + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student has been changed");
        
//        firstName.setText(null);
//        middleName.setText(null);
//        lastName.setText(null);
//        asaSSN.setText(null);
//        attenSecSSN.setText(null);
//        address.setText(null);
//        dob.setText(null);
//        ethnicity.setText(null);
//        commuterType.setText(null);
//        attendance.setText(null);
//        emergencyContact.setText(null);
//        educationPlan.setText(null);
//        homeRoom.setText(null);
//        phoneNumber.setText(null);
//        medInfo.setText(null);
//        parentalContact.setText(null);
//        guardianSSN.setText(null);
//        grade.setText(null);
//        principalSSN.setText(null);
        
        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonAllActionPerformed

    private void EditButtonLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonLastNameActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET LNAME='"+lastName.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student last name has been changed");
        
//        lastName.setText(null);

        stmt.execute(Query);
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonLastNameActionPerformed

    private void EditButtonMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonMiddleNameActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET MNAME='"+middleName.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student middle name has been changed");
        
//        middleName.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonMiddleNameActionPerformed

    private void EditButtonEthnicityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonEthnicityActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET ETHNICITY='"+ethnicity.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student ethnicity has been changed");
        
//        ethnicity.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonEthnicityActionPerformed

    private void EditButtonBIrthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonBIrthdateActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET DOB='"+dob.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student DOB has been changed");
        
//        dob.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonBIrthdateActionPerformed

    private void EditButtonHomeRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonHomeRoomNumberActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET HOMEROOM_NO='"+homeRoom.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student homeroom has been changed");
        
//        homeRoom.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonHomeRoomNumberActionPerformed

    private void EditButtonAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonAttendanceActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET ATTENDENCE='"+attendance.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student attendence has been changed");
        
//        attendance.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonAttendanceActionPerformed

    private void EditButtonEmergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonEmergencyContactActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET EMERGENCY_CONTACT='"+emergencyContact.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student emergency contact has been changed");
        
//        emergencyContact.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonEmergencyContactActionPerformed

    private void EditButtonEducationPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonEducationPlanActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET EDUCATION_PLAN='"+educationPlan.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student education plan has been changed");
        
//        educationPlan.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonEducationPlanActionPerformed

    private void EditButtonPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonPhoneNumberActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET PHONE_NO='"+phoneNumber.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student phone number has been changed");
        
//        phoneNumber.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonPhoneNumberActionPerformed

    private void EditButtonParentalContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonParentalContactActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET PARENTAL_CONTACT='"+parentalContact.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student parental contact has been changed");
        
//        parentalContact.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }    }//GEN-LAST:event_EditButtonParentalContactActionPerformed

    private void EditButtonGuardianSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonGuardianSSNActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET STU_GUARDIAN_SSN='"+guardianSSN.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student guardian SSN has been changed");
        
//        guardianSSN.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonGuardianSSNActionPerformed

    private void EditButtonAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonAddressActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET ADDRESS='"+address.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student address has been changed");
        
//        address.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonAddressActionPerformed

    private void EditButtonCommuterTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonCommuterTypeActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET COMMUTER_TYPE='"+commuterType.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student commute type has been changed");
        
//        commuterType.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonCommuterTypeActionPerformed

    private void EditButtonGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonGradeActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET STU_GRADE_ID='"+grade.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student grade has been changed");
        
//        grade.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonGradeActionPerformed

    private void EditButtonPrincipalSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonPrincipalSSNActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET STU_P_SSN='"+principalSSN.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student principal SSN has been changed");
        
//        principalSSN.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonPrincipalSSNActionPerformed

    private void EditButtonASASSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonASASSNActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET STU_ASA_SSN='"+asaSSN.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student ASA SSN has been changed");
        
//        asaSSN.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonASASSNActionPerformed

    private void EditButtonAttenSecSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonAttenSecSSNActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET STU_ATTEN_SEC_SSN='"+attenSecSSN.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student attendant secretary SSN has been changed");
        
//        attenSecSSN.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonAttenSecSSNActionPerformed

    private void EditButtonMedicationInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonMedicationInformationActionPerformed
        try {
            
        Connection connection = DriverManager.getConnection(url, username, password); 
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE STUDENT "
                + "SET MEDICAL_INFORMATION='"+medInfo.getText()+"' "
                + "WHERE STUDENT_ID='"+studentID.getText()+"'";
        
        JOptionPane.showMessageDialog(null, "Student medical information has been changed");
        
//        medInfo.setText(null);

        stmt.execute(Query);
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_EditButtonMedicationInformationActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new Edit().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ViewStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStaffButtonActionPerformed
        try {
            Connection connection = DriverManager.getConnection(url, username, password); 
            String Query = "USE cpetza1db";  // Select the database
            Statement stmt = connection.createStatement();
            stmt.execute(Query);
            String query1 = "SELECT STUDENT_ID, FNAME, MNAME, LNAME,"
            + " STU_ASA_SSN, STU_ATTEN_SEC_SSN, ADDRESS, PARENTAL_CONTACT, DOB,"
            + " ETHNICITY FROM STUDENT";
            PreparedStatement pstmt = connection.prepareStatement(query1);
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel)studentTable1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                    rs.getString(8), rs.getString(9), rs.getString(10)});
        }
        String query2 = "SELECT STUDENT_ID, COMMUTER_TYPE, ATTENDENCE, EMERGENCY_CONTECT, EDUCATION_PLAN,"
        + " HOMEROOM_NO, PHONE_NO, MEDICAL_INFORMATION, STU_GUARDIAN_SSN, STU_GRADE_ID,"
        + " STU_P_SSN FROM STUDENT";
        PreparedStatement pstmt2 = connection.prepareStatement(query2);
        ResultSet rs2 = pstmt2.executeQuery();
        DefaultTableModel model2 = (DefaultTableModel)studentTable2.getModel();
        model2.setRowCount(0);
        while(rs2.next()){
            model2.addRow(new String[]{rs2.getString(1), rs2.getString(2),
                rs2.getString(3), rs2.getString(4), rs2.getString(5), rs2.getString(6), rs2.getString(7),
                rs2.getString(8), rs2.getString(9), rs2.getString(10), rs2.getString(11)});
        }
        } catch(SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_ViewStaffButtonActionPerformed
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddButton1;
    private javax.swing.JButton AddButton10;
    private javax.swing.JButton AddButton11;
    private javax.swing.JButton AddButton12;
    private javax.swing.JButton AddButton13;
    private javax.swing.JButton AddButton14;
    private javax.swing.JButton AddButton15;
    private javax.swing.JButton AddButton16;
    private javax.swing.JButton AddButton17;
    private javax.swing.JButton AddButton18;
    private javax.swing.JButton AddButton19;
    private javax.swing.JButton AddButton2;
    private javax.swing.JButton AddButton20;
    private javax.swing.JButton AddButton4;
    private javax.swing.JButton AddButton5;
    private javax.swing.JButton AddButton6;
    private javax.swing.JButton AddButton7;
    private javax.swing.JButton AddButton8;
    private javax.swing.JButton AddButton9;
    private javax.swing.JButton ViewStaffButton;
    private javax.swing.JTextField address;
    private javax.swing.JTextField asaSSN;
    private javax.swing.JTextField attenSecSSN;
    private javax.swing.JTextField attendance;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField commuterType;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField educationPlan;
    private javax.swing.JTextField emergencyContact;
    private javax.swing.JTextField ethnicity;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField grade;
    private javax.swing.JTextField guardianSSN;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField homeRoom;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField medInfo;
    private javax.swing.JTextField middleName;
    private javax.swing.JTextField parentalContact;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField principalSSN;
    private javax.swing.JTextField studentID;
    private javax.swing.JTable studentTable1;
    private javax.swing.JTable studentTable2;
    // End of variables declaration//GEN-END:variables
}
