/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarksburgdbms.actionforms.edit;
import clarksburgdbms.Main;
import clarksburgdbms.choiceforms.Edit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EditGuardian extends javax.swing.JFrame {

    /**
     * Creates new form EditGuardian
     */
    
   Connection connection;
    
    public EditGuardian() {
        initComponents();
        
        String url = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/cpetza1db";
        String username = "cpetza1";
        String password = "COSC*l1j11";
        
        try {
            connection = DriverManager.getConnection(url, username, password); 
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        guardianID = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        guardianAddButton = new javax.swing.JButton();
        guardianAddButton2 = new javax.swing.JButton();
        guardianAddButton3 = new javax.swing.JButton();
        guardianAddButton4 = new javax.swing.JButton();
        guardianAddButton5 = new javax.swing.JButton();
        guardianAddButton6 = new javax.swing.JButton();
        guardianAddButton7 = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        guardianTable = new javax.swing.JTable();
        ViewGuardiansButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Edit Guardian");

        jLabel2.setText("Guardian ID");

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Address");

        jLabel6.setText("Email");

        jLabel7.setText("Phone Number");

        jLabel9.setText("Middle Name");

        guardianAddButton.setText("Edit All");
        guardianAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianEditAllButtonActionPerformed(evt);
            }
        });

        guardianAddButton2.setText("Edit");
        guardianAddButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianEditMiddleNameButtonActionPerformed(evt);
            }
        });

        guardianAddButton3.setText("Edit");
        guardianAddButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianEditFirstNameButtonActionPerformed(evt);
            }
        });

        guardianAddButton4.setText("Edit");
        guardianAddButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianEditLastNameButtonActionPerformed(evt);
            }
        });

        guardianAddButton5.setText("Edit");
        guardianAddButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianEditEmailButtonActionPerformed(evt);
            }
        });

        guardianAddButton6.setText("Edit");
        guardianAddButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianEditAddressButtonActionPerformed(evt);
            }
        });

        guardianAddButton7.setText("Edit");
        guardianAddButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianEditPhoneNumberButtonActionPerformed(evt);
            }
        });

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        guardianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Gaurdian ID", "First", "Middle", "Last", "Address", "Email", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(guardianTable);

        ViewGuardiansButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewGuardiansButton.setText("View Guardians");
        ViewGuardiansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGuardiansButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(guardianAddButton7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(guardianAddButton5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(guardianAddButton6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(guardianAddButton4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(guardianAddButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(guardianID, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(guardianAddButton3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(guardianAddButton)
                                .addGap(270, 270, 270)
                                .addComponent(ViewGuardiansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianAddButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianAddButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianAddButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianAddButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianAddButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianAddButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardianAddButton)
                            .addComponent(ViewGuardiansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(homeButton)
                        .addComponent(backButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void guardianEditAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianEditAllButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE GUARDIAN "
                + "SET "
                    + "FNAME='"+fname.getText()+"', "
                    + "MNAME='"+mname.getText()+"', "
                    + "LNAME='"+lname.getText()+"', "
                    + "ADDRESS='"+address.getText()+"', "
                    + "EMAIL_ADDRESS='"+email.getText()+"', "
                    + "PHONE_NO='"+phoneNumber.getText()+"' "
                    + "WHERE GUARDIAN_ID='"+guardianID.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Guardian has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        fname.setText(null);
        mname.setText(null);
        lname.setText(null);
        address.setText(null);
        email.setText(null);
        phoneNumber.setText(null);
       
        // Adds the query to the Database
        stmt.execute(Query);
        
        // Close connection to Database
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_guardianEditAllButtonActionPerformed

    private void guardianEditMiddleNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianEditMiddleNameButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE GUARDIAN "
                + "SET MNAME='" + mname.getText() + "' "
                + "WHERE GUARDIAN_ID='" + guardianID.getText() + "'";
                                
        JOptionPane.showMessageDialog(null, "Guardian middle name has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        mname.setText(null);
       
        // Adds the query to the Database
        stmt.execute(Query);
        
        // Close connection to Database
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_guardianEditMiddleNameButtonActionPerformed

    private void guardianEditFirstNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianEditFirstNameButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE GUARDIAN "
                + "SET FNAME='" + fname.getText() + "' "
                + "WHERE GUARDIAN_ID='" + guardianID.getText() + "'";
                                
        JOptionPane.showMessageDialog(null, "Guardian first name has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        fname.setText(null);
       
        // Adds the query to the Database
        stmt.execute(Query);
        
        // Close connection to Database
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_guardianEditFirstNameButtonActionPerformed

    private void guardianEditLastNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianEditLastNameButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE GUARDIAN "
                + "SET LNAME='"+lname.getText()+"' "
                + "WHERE GUARDIAN_ID='"+guardianID.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Guardian last name has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        lname.setText(null);
       
        // Adds the query to the Database
        stmt.execute(Query);
        
        // Close connection to Database
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_guardianEditLastNameButtonActionPerformed

    private void guardianEditEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianEditEmailButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE GUARDIAN "
                + "SET EMAIL_ADDRESS='"+email.getText()+"' "
                + "WHERE GUARDIAN_ID='"+guardianID.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Guardian email address has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        email.setText(null);
       
        // Adds the query to the Database
        stmt.execute(Query);
        
        // Close connection to Database
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_guardianEditEmailButtonActionPerformed

    private void guardianEditAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianEditAddressButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE GUARDIAN "
                + "SET ADDRESS='"+address.getText()+"' "
                + "WHERE GUARDIAN_ID='"+guardianID.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Guardian address has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        address.setText(null);
       
        // Adds the query to the Database
        stmt.execute(Query);
        
        // Close connection to Database
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_guardianEditAddressButtonActionPerformed

    private void guardianEditPhoneNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianEditPhoneNumberButtonActionPerformed
        try {
        
        Statement stmt = connection.createStatement();
        
        stmt.execute("USE cpetza1db");
        
        String Query = "UPDATE GUARDIAN "
                + "SET PHONE_NO='"+phoneNumber.getText()+"' "
                + "WHERE GUARDIAN_ID='"+guardianID.getText()+"'";
                                
        JOptionPane.showMessageDialog(null, "Guardian phone number has been changed");
        
        // Reset all fields to null (Comment out if you want to do lots of additions)
        phoneNumber.setText(null);
       
        // Adds the query to the Database
        stmt.execute(Query);
        
        // Close connection to Database
//        connection.close();
        
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.toString());
        }
    }//GEN-LAST:event_guardianEditPhoneNumberButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new Edit().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ViewGuardiansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGuardiansButtonActionPerformed
        try {
        String Query = "USE cpetza1db";  // Select the database
            Statement stmt = connection.createStatement();
            stmt.execute(Query);
        String query = "SELECT * FROM GUARDIAN";
            PreparedStatement pstmt = connection.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel)guardianTable.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),
                rs.getString(5), rs.getString(6), rs.getString(7)});
            }
        } catch(SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_ViewGuardiansButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGuardian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewGuardiansButton;
    private javax.swing.JTextField address;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton guardianAddButton;
    private javax.swing.JButton guardianAddButton2;
    private javax.swing.JButton guardianAddButton3;
    private javax.swing.JButton guardianAddButton4;
    private javax.swing.JButton guardianAddButton5;
    private javax.swing.JButton guardianAddButton6;
    private javax.swing.JButton guardianAddButton7;
    private javax.swing.JTextField guardianID;
    private javax.swing.JTable guardianTable;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField phoneNumber;
    // End of variables declaration//GEN-END:variables
}
