/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarksburgdbms;

import clarksburgdbms.choiceforms.*;

/**
 *
 * @author Quentin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    Boolean searchChecked = false;
    Boolean insertChecked = false;
    Boolean editChecked = false;
    Boolean deleteChecked = false;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchRadio = new javax.swing.JRadioButton();
        InsertRadio = new javax.swing.JRadioButton();
        DeleteRadio = new javax.swing.JRadioButton();
        GoButton = new javax.swing.JButton();
        DeleteRadio1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setText("Clarksburg Elementary");

        jLabel2.setText("What would you like to do?");

        buttonGroup1.add(SearchRadio);
        SearchRadio.setText("Search");
        SearchRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(InsertRadio);
        InsertRadio.setText("Insert");
        InsertRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(DeleteRadio);
        DeleteRadio.setText("Edit");
        DeleteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRadioActionPerformed(evt);
            }
        });

        GoButton.setText("Go");
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(DeleteRadio1);
        DeleteRadio1.setText("Delete");
        DeleteRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeleteRadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsertRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(GoButton)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchRadio)
                    .addComponent(InsertRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRadio)
                    .addComponent(DeleteRadio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GoButton)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertRadioActionPerformed
        insertChecked = !insertChecked;
    }//GEN-LAST:event_InsertRadioActionPerformed

    private void SearchRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRadioActionPerformed
        searchChecked = !searchChecked;
    }//GEN-LAST:event_SearchRadioActionPerformed

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButtonActionPerformed
        if(!insertChecked && !searchChecked && !editChecked && !deleteChecked){
           
        }
        else if(insertChecked && !searchChecked && !editChecked && !deleteChecked){
            dispose();
            new Insert().setVisible(true);
            
        }
        else if(!insertChecked && searchChecked && !editChecked && !deleteChecked){
            dispose();
            new Search().setVisible(true);
        }
        else if(!insertChecked && !searchChecked && editChecked && !deleteChecked) {
            dispose();
            new Edit().setVisible(true);
        }
        else if(!insertChecked && !searchChecked && !editChecked && deleteChecked){
            dispose();
            new Delete().setVisible(true);
        }
    }//GEN-LAST:event_GoButtonActionPerformed

    private void EditRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRadioActionPerformed
        editChecked = !editChecked;
    }//GEN-LAST:event_EditRadioActionPerformed

    private void DeleteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRadioActionPerformed
        deleteChecked = !deleteChecked;
    }//GEN-LAST:event_DeleteRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DeleteRadio;
    private javax.swing.JRadioButton DeleteRadio1;
    private javax.swing.JButton GoButton;
    private javax.swing.JRadioButton InsertRadio;
    private javax.swing.JRadioButton SearchRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
