/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarksburgdbms.choiceforms;
import clarksburgdbms.Main;
import clarksburgdbms.actionforms.delete.DeleteGuardian;
import clarksburgdbms.actionforms.delete.DeleteStaff;
import clarksburgdbms.actionforms.delete.DeleteStudent;
import clarksburgdbms.actionforms.insert.AddGuardian;
import clarksburgdbms.actionforms.insert.AddStaff;
import clarksburgdbms.actionforms.insert.AddStudent;
/**
 *
 * @author Quentin
 */
public class Delete extends javax.swing.JFrame {
    boolean staffSelected = false;
    boolean studentSelected = false;
    boolean guardianSelected = false;

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        staffRadio = new javax.swing.JRadioButton();
        HomeButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        guardianRadio = new javax.swing.JRadioButton();
        studentRadio1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setText("Delete");

        buttonGroup1.add(staffRadio);
        staffRadio.setText("Staff");
        staffRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffRadioActionPerformed(evt);
            }
        });

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(guardianRadio);
        guardianRadio.setText("Guardian");
        guardianRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(studentRadio1);
        studentRadio1.setText("Student");
        studentRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRadio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HomeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(staffRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(goButton)
                                    .addComponent(studentRadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(guardianRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeButton)
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffRadio)
                    .addComponent(guardianRadio)
                    .addComponent(studentRadio1))
                .addGap(18, 18, 18)
                .addComponent(goButton)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffRadioActionPerformed
        staffSelected = !staffSelected;
    }//GEN-LAST:event_staffRadioActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        if (!staffRadio.isSelected() && !studentRadio1.isSelected() && !guardianRadio.isSelected()) {
            //do nothing
        } else if (!staffRadio.isSelected() && studentRadio1.isSelected() && !guardianRadio.isSelected()) {
            dispose();
            new DeleteStudent().setVisible(true);
        } else if (staffRadio.isSelected() && !studentRadio1.isSelected() && !guardianRadio.isSelected()) {
            dispose();
            new DeleteStaff().setVisible(true);
        } else if (!staffRadio.isSelected() && !studentRadio1.isSelected() && guardianRadio.isSelected()) {
            dispose();
            new DeleteGuardian().setVisible(true);
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void guardianRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianRadioActionPerformed
        guardianSelected = !guardianSelected;
    }//GEN-LAST:event_guardianRadioActionPerformed

    private void studentRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadio1ActionPerformed
        studentSelected = !studentSelected;
    }//GEN-LAST:event_studentRadio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton goButton;
    private javax.swing.JRadioButton guardianRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton staffRadio;
    private javax.swing.JRadioButton studentRadio1;
    // End of variables declaration//GEN-END:variables
}
