/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarksburgdbms.choiceforms;

import clarksburgdbms.Main;
import clarksburgdbms.actionforms.edit.*;

/**
 *
 * @author Quentin
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        StaffRadio = new javax.swing.JRadioButton();
        StudentRadio = new javax.swing.JRadioButton();
        HomeButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        GuardianRadio = new javax.swing.JRadioButton();
        GradeLevelRadio = new javax.swing.JRadioButton();
        GradeReportRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setText("Edit");

        buttonGroup1.add(StaffRadio);
        StaffRadio.setText("Staff");

        buttonGroup1.add(StudentRadio);
        StudentRadio.setText("Student");

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        GuardianRadio.setText("Guardian");

        buttonGroup1.add(GradeLevelRadio);
        GradeLevelRadio.setText("Grade level");

        buttonGroup1.add(GradeReportRadio);
        GradeReportRadio.setText("Grade report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GradeLevelRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GradeReportRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(goButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StaffRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StudentRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GuardianRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HomeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffRadio)
                    .addComponent(GuardianRadio)
                    .addComponent(StudentRadio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradeLevelRadio)
                    .addComponent(GradeReportRadio))
                .addGap(47, 47, 47)
                .addComponent(goButton)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        if (!StudentRadio.isSelected() && !StaffRadio.isSelected() && !GuardianRadio.isSelected() && !GradeReportRadio.isSelected() && !GradeLevelRadio.isSelected()) {
            //do nothing
        } else if (StudentRadio.isSelected() && !StaffRadio.isSelected() && !GuardianRadio.isSelected() && !GradeReportRadio.isSelected() && !GradeLevelRadio.isSelected()) {
            dispose();
            new EditStudent().setVisible(true);
        } else if (!StudentRadio.isSelected() && StaffRadio.isSelected() && !GuardianRadio.isSelected() && !GradeReportRadio.isSelected() && !GradeLevelRadio.isSelected()) {
            dispose();
            new EditStaff().setVisible(true);
        } else if (!StudentRadio.isSelected() && !StaffRadio.isSelected() && GuardianRadio.isSelected() && !GradeReportRadio.isSelected() && !GradeLevelRadio.isSelected()) {
            dispose();
            new EditGuardian().setVisible(true);
        } else if (!StudentRadio.isSelected() && !StaffRadio.isSelected() && !GuardianRadio.isSelected() && GradeReportRadio.isSelected() && !GradeLevelRadio.isSelected()) {
            dispose();
            new EditGradeReport().setVisible(true);
        } else if (!StudentRadio.isSelected() && !StaffRadio.isSelected() && !GuardianRadio.isSelected() && !GradeReportRadio.isSelected() && GradeLevelRadio.isSelected()) {
            dispose();
            new EditGradeLevel().setVisible(true);
        }
    }//GEN-LAST:event_goButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GradeLevelRadio;
    private javax.swing.JRadioButton GradeReportRadio;
    private javax.swing.JRadioButton GuardianRadio;
    private javax.swing.JButton HomeButton;
    private javax.swing.JRadioButton StaffRadio;
    private javax.swing.JRadioButton StudentRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
